Update for SIG tutorial
netsec-ethz/scion-tutorials pull request #144
Opened 2020-04-09 16:20 UTC by slab14

This updates the SIG tutorial document (remote_sig.md) to reflect the recent changes to scionlab. This was based on PR #134 and should fix the concerns with that PR.

2020-04-14 10:15 UTC, FR4NK-W requested changes
Thanks for the PR
Only minor comments

2020-04-14 10:15 UTC, FR4NK-W commented on content/apps/remote_sig.md
> +Building the SIG binary requires go version 1.13. This is newer than many default packages, and can be installed as followed.
I think it makes more sense to refer to the `building from source` docs page:
https://docs.scionlab.org/content/install/src.html
for building. The Go version is given by the go.mod file.
This also prevents people from ending up with duplicate entries in their .profile and makes it easier to update the build instructions.

2020-04-14 10:16 UTC, FR4NK-W commented on content/apps/remote_sig.md
> +export AS=$( ls /etc/scion/gen/ISD${ISD}/ | grep AS | awk -F 'AS' '{ print $2 }')
>AS=$( ls

Stray space

2020-04-14 14:36 UTC, slab14 commented
Thanks for the comments, updated to address.

2020-04-15 17:46 UTC, slab14 reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/144)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @FR4NK-W)

___
*[content/apps/remote_sig.md, line 16 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/144#-M4Uj_G9G_WCGTsCyGPZ-r1-16:-M4yvtJj9vvIIkQ29plN:b-7t22qw) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/1f2a4db3a1e0d694cd0bcfc0db1cb55f0615bb47/content/apps/remote_sig.md#L16)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

I think it makes more sense to refer to the `building from source` docs page:
https://docs.scionlab.org/content/install/src.html
for building. The Go version is given by the go.mod file.
This also prevents people from ending up with duplicate entries in their .profile and makes it easier to update the build instructions.
</blockquote></details>

Good point. I removed the reference to a specific Go version (and download) and referenced the `build from source` docs to get the correct Go version. Done.
___
*[content/apps/remote_sig.md, line 45 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/144#-M4Uj_G9G_WCGTsCyGPZ-r1-45:-M4yvu8k3cf0vY3b4ioK:b-lceayv) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/1f2a4db3a1e0d694cd0bcfc0db1cb55f0615bb47/content/apps/remote_sig.md#L45)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>AS=$( ls

Stray space
</blockquote></details>

Space removed. Done.


<!-- Sent from Reviewable.io -->

2020-04-15 18:31 UTC, slab14 reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/144)* status: all files reviewed, 2 unresolved discussions (waiting on @FR4NK-W)



<!-- Sent from Reviewable.io -->

2020-04-16 14:27 UTC, FR4NK-W approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/144)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-16 14:28 UTC, merged