Sigcomm tasks
netsec-ethz/scion-tutorials pull request #166
Opened 2020-08-12 14:47 UTC by juagargi

- [ ] validate with Markus
- [ ] validate with SCIONLab

2020-08-12 20:34 UTC, mlegner reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 20 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 19 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYCTwq1Wb5dFAhbwUj:-MEYCTwr0-76LFg4l4uK:b-39vxbi) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L19)):*
> ```Markdown
> ```
> 
> Some messages will be displayed, indicating the progress of the VM creation. The command should exit with zero (you can check with `echo $?` right after `vagrant up` has finished).
> ```

Should we mention here (or somewhere at the beginning) that they should contact us if they don't see the expected results?
___
*[content/sigcomm/workshop.md, line 52 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGQ6rD9vaInwMw1jY:-MEYGQ6rD9vaInwMw1jZ:bhzow84) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L52)):*
> ```
> As mentioned in the [preparation guide](preparation.html), all the sections in the health check should be passing, and displayed in green.
> ```
We now have the `scmp-echo` in the preparation guide.
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGlQT6h0dcvhya9kp:-MEYGlQT6h0dcvhya9kq:b-3k3exy) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
> ```Markdown
> With that, the web application should be running inside the VM, listening for connections on port `8000`. Because the VM is configured to forward that port, you can already connect from your host machine at [http://localhost:8000]. In this page, the health status of your user AS is displayed. As mentioned in the [preparation guide](preparation.html), all the sections in the health check should be passing, and displayed in green.
> 
> Go to the page *Apps* and select one of the apps (*bwtester*, *camerapp*, *sensorapp*). You should not need to change the source settings but you can select any of the ASes preconfigured in the list as destination or could enter the information of any of your colleagues' ASes.
> ```

Could we briefly mention what they do (or link to the more specific tutorial pages)?
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGz64CcqaaaounOiN:-MEYGz64CcqaaaounOiO:b-s8fhq9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
> ```
> *bwtester*
> ```
Should we mention that they shouldn't attempt too high throughput?
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHL7319kNcCzNsF2X:-MEYHL7319kNcCzNsF2Y:bahcab5) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
> ```
> ASes preconfigured in the list
> ```
When running the sensorapp for `17-ffaa:1:13`, I get an error: `Path lookup had an error err_code="SCIOND experienced an internal error"`
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYH_hK-ggxJYi7WQ6P:-MEYH_hK-ggxJYi7WQ6Q:bfti8vl) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
> ```
> *camerapp*
> ```
How much work would it be to set up another cameraserver?
___
*[content/sigcomm/workshop.md, line 56 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHv3DCppCCCNvIXGX:-MEYHv3DCppCCCNvIXGY:b-sgy9zm) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L56)):*
> ```
> *Paths*
> ```
Can we mention the SCIONLab topology on the main scionlab website?
___
*[content/sigcomm/workshop.md, line 58 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIK-g6fUA9eaF49Yf:-MEYIK-g6fUA9eaF49Yg:b1xyoz2) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L58)):*
> ```
> TRC
> ```
The TRC doesn't look very interesting to me...
___
*[content/sigcomm/workshop.md, line 60 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYJ0Yj6Zi7FWwHyDIV:-MEYJ0Yk-ORK-scQwSqs:bm5hkpg) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L60)):*
> ```Markdown
> The web application also allows you to look at the TRC of your ISD as well as your certificate and the SCION services running in your AS
> 
> #### From a shell inside your VM
> ```

Can we already mention the `showpaths` tool that is mentioned later?
___
*[content/sigcomm/workshop.md, line 64 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYITCj5W10YRrOrBzH:-MEYITCj5W10YRrOrBzI:b-1yx9ph) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L64)):*
> ```Markdown
> Inside your VM, you can explore several subdirectories:
> 
> + The directory `/etc/scion/gen/` contains configuration files for you AS such as the local topology.
> ```

Some information about the topology file and its contents could be helpful.
___
*[content/sigcomm/workshop.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIdCLEmiKu0JnI-vP:-MEYIdCLEmiKu0JnI-vQ:b-ryc4iz) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L65)):*
> ```Markdown
> 
> + The directory `/etc/scion/gen/` contains configuration files for you AS such as the local topology.
> + The directory `/var/log/scion/` allows you to access logs of the different SCION services. In particular the control service's log `cs*-1.log` can be interesting.
> ```

What should they look for?
___
*[content/sigcomm/workshop.md, line 74 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIsgl4a5G626s9st8:-MEYIsgl4a5G626s9st9:b95v6q1) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L74)):*
> ```Markdown
> + sensorserver at `17-ffaa:0:1102,[192.33.93.177]:42003`
> + cameraserver at `17-ffaa:0:1102,[192.33.93.166]:42002`
> + bwtestserver at [list of bwtestservers](http://localhost:4000/content/apps/bwtester.html#scionlab-bandwidth-test-servers)
> ```

This link seems to be wrong.
___
*[content/sigcomm/workshop.md, line 80 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYK-dA5LXrR7McPYv0:-MEYK-dA5LXrR7McPYv1:b-2xadpp) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L80)):*
> ```Markdown
> <!-- Using the tool `bat` that works similar to `curl` you can also download the tutorial page running at `1-ff00:0:1,[127.0.0.1]:9090`. Consult the respective tutorial page for details. -->
> 
> ### Run your own SCION apps
> ```

We can tell them to post their ISD-AS numbers and the services they offer on Slack so that their colleagues can connect to them.
___
*[content/sigcomm/workshop.md, line 84 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYJwWFDlTDWpVph1g5:-MEYJwWFDlTDWpVph1g6:b-27cjeh) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L84)):*
> ```
> *How to use* -> *Bandwidth tester application*
> ```
Replace by direct link?
___
*[content/sigcomm/workshop.md, line 88 at r2](https://r [...]

2020-08-13 09:38 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 93 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEbAkQYCb-HrKVsrBcN:-MEbAkQYCb-HrKVsrBcO:b-fzznjf) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L93)):*
> ```Markdown
> ### Set up an additional peering link with your second user AS
> 
> #### Configure a second user AS
> ```

We can suggest that they set it up with a different attachment point to make the results even more interesting (the latency difference).


<!-- Sent from Reviewable.io -->

2020-08-13 09:42 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 166 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEZLTlN2_aDadQ78qPe:-MEbBlXq7eKdN8LOof_t:b2sadds) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L166)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Can we provide a one-liner here?
</blockquote></details>

I can take care of that.


<!-- Sent from Reviewable.io -->

2020-08-13 09:45 UTC, juagargi reviewed
I am having an issue with the health check after I have modified the VMs with the private interface.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-:-MEaxqUNARgU-Z5gM33a:b-5r5wfw)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 19 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYCTwq1Wb5dFAhbwUj:-MEatfVi7Jk9BvVuHJMV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L19)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Should we mention here (or somewhere at the beginning) that they should contact us if they don't see the expected results?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 52 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGQ6rD9vaInwMw1jY:-MEauS4OAd_dcU4gbDo-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L52)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> As mentioned in the [preparation guide](preparation.html), all the sections in the health check should be passing, and displayed in green.
> ```
We now have the `scmp-echo` in the preparation guide.
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGlQT6h0dcvhya9kp:-MEavif11rqVOkHT26hc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Could we briefly mention what they do (or link to the more specific tutorial pages)?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYGz64CcqaaaounOiN:-MEavzSPARUtWkr6FAcN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> *bwtester*
> ```
Should we mention that they shouldn't attempt too high throughput?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHL7319kNcCzNsF2X:-MEaxGo41D98h6l7e7Zb:b-99og7v) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> ASes preconfigured in the list
> ```
When running the sensorapp for `17-ffaa:1:13`, I get an error: `Path lookup had an error err_code="SCIOND experienced an internal error"`
</blockquote></details>

I OTOH get paths, but don't see any readings.
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYH_hK-ggxJYi7WQ6P:-MEaxafpByTUdhqC2N16:bb2pnfq) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> *camerapp*
> ```
How much work would it be to set up another cameraserver?
</blockquote></details>

I don't know, but should be relatively easy. If we have a raspberry pi with camera, even better. Otherwise we have to just return images.
___
*[content/sigcomm/workshop.md, line 56 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHv3DCppCCCNvIXGX:-MEaykVn9PTN4S1PuKqI:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L56)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> *Paths*
> ```
Can we mention the SCIONLab topology on the main scionlab website?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 58 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIK-g6fUA9eaF49Yf:-MEb0tHSDCTRg9j4zJqw:b-2017en) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L58)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> TRC
> ```
The TRC doesn't look very interesting to me...
</blockquote></details>

Added how to decode it.
___
*[content/sigcomm/workshop.md, line 60 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYJ0Yj6Zi7FWwHyDIV:-MEb1tfu9P244nDkL1VJ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L60)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Can we already mention the `showpaths` tool that is mentioned later?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 64 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYITCj5W10YRrOrBzH:-MEb5XCD6kt6Nf7XAaTD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L64)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Some information about the topology file and its contents could be helpful.
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIdCLEmiKu0JnI-vP:-MEb6CGn0FzLAxxl-Leg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L65)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

What should they look for?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 74 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIsgl4a5G626s9st8:-MEb7HIQAwaRRzSNpvOa:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L74)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This link seems to be wrong.
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 80 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYK-dA5LXrR7McPYv0:-MEb8b-X5ML49K3GZwaU:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L80)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We can tell them to post their ISD-AS numbers and the services they offer on Slack so that their colleagues can connect to them.
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 84 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYJwWFDlTDWpVph1g5:-MEb82vkCMMTr7iu3q4e:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L84)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

> ```
> *How to use* -> *Bandwidth tester application*
> ```
Replace by direct link?
</blockquote></details>

Done.
___
*[content/sigcomm/workshop.md, line 88 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYKx5f51QsBO8z-uCk:-MEb9E9p5H6ZkPciHWI8:b-896fix) ([raw file](https:/ [...]

2020-08-13 09:52 UTC, mlegner reviewed
Looks fine for me...

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-:-MEbDu0Z3DOGcWb13zkM:b-v9jdzq)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @juagargi and @mlegner)



<!-- Sent from Reviewable.io -->

2020-08-13 09:52 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 93 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEbAkQYCb-HrKVsrBcN:-MEbCj033SlhncPHZm49:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L93)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We can suggest that they set it up with a different attachment point to make the results even more interesting (the latency difference).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-13 10:16 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHL7319kNcCzNsF2X:-MEbHbBuEn8LM1l-UXPi:b-yk7zju) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I OTOH get paths, but don't see any readings.
</blockquote></details>

Maybe it's not properly running there?
___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYH_hK-ggxJYi7WQ6P:-MEbHepQ3skWjn1KMeJH:bvrk8dj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I don't know, but should be relatively easy. If we have a raspberry pi with camera, even better. Otherwise we have to just return images.
</blockquote></details>

OK, let's keep this in mind for the (unlikely case) that we will have the time to set it up tomorrow.
___
*[content/sigcomm/workshop.md, line 58 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIK-g6fUA9eaF49Yf:-MEbHsoM3yExe7tOIm5l:b-zc0taj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L58)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Added how to decode it.
</blockquote></details>

Great. It would be nice if the webapp did this for us; should I open an issue in that repo?


<!-- Sent from Reviewable.io -->

2020-08-13 11:54 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 225 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEZMNK1-LIHKLp2pga0:-MEbeUpw0y_fzl9dbyuo:bitj7di) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L225)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This didn't work for me right now, but maybe I'm just too tired at the moment. Will try again tomorrow (probably made a small mistake).
</blockquote></details>

OK, I incorrectly edited the topology file, it works now.
___
*[content/sigcomm/workshop.md, line 271 at r5](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEbesKb28dqOwt-5eON:-MEbesKb28dqOwt-5eOO:beiwarp) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/110e6544238e4ef163031765fc69aecbda26071d/content/sigcomm/workshop.md#L271)):*
> ```Markdown
> + Save the modified topology file
> + Copy the modified topology file into all subdirectories of `/etc/scion/gen/ISD*/AS*/` (all other services need to know the new topology) `sudo cp topology.json ../br*/ ; sudo cp topology.json ../cs*/`.
> + Restart SCION by calling `sudo systemctl restart scionlab.target`; you may also have to remove the contents of the directory `/etc/scion/gen-cache/`
> ```

I don't even have this directory...


<!-- Sent from Reviewable.io -->

2020-08-13 11:59 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 58 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIK-g6fUA9eaF49Yf:-MEbfDxG8fgD2TrRDzG6:b-n0tjw8) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L58)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Great. It would be nice if the webapp did this for us; should I open an issue in that repo?
</blockquote></details>

yes please
___
*[content/sigcomm/workshop.md, line 271 at r5](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEbesKb28dqOwt-5eON:-MEbg4rG3OQJX1cgok6u:b-sji97l) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/110e6544238e4ef163031765fc69aecbda26071d/content/sigcomm/workshop.md#L271)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I don't even have this directory...
</blockquote></details>

It's wrong. Fixed now.


<!-- Sent from Reviewable.io -->

2020-08-13 12:01 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 54 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYHL7319kNcCzNsF2X:-MEbgT-t9zxTB8u9JU8X:b-z9c3dr) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L54)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Maybe it's not properly running there?
</blockquote></details>

Sent an email to Adrian to find out what happens with the machine.


<!-- Sent from Reviewable.io -->

2020-08-13 12:46 UTC, juagargi reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 242 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEZMWE19_UyPkmuYxVc:-MEbqgQCCr4UDXF-UDlY:b7sqb6w) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L242)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We haven't discussed this yet, so we may need to link to the tutorial describing port forwarding etc. in more detail.
</blockquote></details>

It's now a bonus exercise.


<!-- Sent from Reviewable.io -->

2020-08-13 13:01 UTC, mlegner reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 58 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEYIK-g6fUA9eaF49Yf:-MEbtV_tDq0y1JQegwbY:blgjdqj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40940c371e3e5f6223dd0f04a6433c89bc2afee0/content/sigcomm/workshop.md#L58)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

yes please
</blockquote></details>

OK: https://github.com/netsec-ethz/scion-apps/issues/165


<!-- Sent from Reviewable.io -->

2020-08-13 13:42 UTC, mlegner reviewed
Looks all good to me so far. :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-:-MEc2SYS6D7iANjb1jC9:b-4dxvsz)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @juagargi)



<!-- Sent from Reviewable.io -->

2020-08-13 13:47 UTC, mlegner reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-13 21:25 UTC, mlegner requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 197 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhYZY6IBQ5FNgFDzk:-MEdhYZY6IBQ5FNgFDzl:b6mqm04) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L197)):*
> ```Markdown
> There is a simple web server that runs in a computer under the following address:
> ```
> 18-ffaa:0:1201,128.237.152.165:4443/
> ```

This doesn't work for me yet. Is it already running?
___
*[content/sigcomm/workshop.md, line 209 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhb_01GPRbcvkYZyq:-MEdhb_01GPRbcvkYZyr:b-x3ufhj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L209)):*
> ```Markdown
> There is an IP regular http server running on:
> ```
> http://128.237.152.165:4443/
> ```

What is the point of this server? Should it be accessible over the SIG?


<!-- Sent from Reviewable.io -->

2020-08-14 07:53 UTC, juagargi reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: all files reviewed, 2 unresolved discussions (waiting on @mlegner)

___
*[content/sigcomm/workshop.md, line 197 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhYZY6IBQ5FNgFDzk:-MEfx99P3hkt0gyH3rPj:b45r8tj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L197)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This doesn't work for me yet. Is it already running?
</blockquote></details>

it was down. This was in the log file:
```
starting SCION server on Thu Aug 13 15:48:18 UTC 2020
t=2020-08-13T15:48:18+0000 lvl=dbug msg="Registered with dispatcher" addr=18-ffaa:0:1201,128.237.152.165:4443
2020/08/13 15:52:33 19-ffaa:1:108,127.0.0.1:6876 "GET / HTTP/3/SCION" 200 20760
t=2020-08-13T15:52:44+0000 lvl=info msg="Received SCMP revocation" header="Class=PATH(3) Type=REVOKED_IF(4) TotalLen=296B Checksum=a612 Timestamp=2020-08-13 15:52:43.992268 +0000 UTC" payload="Meta: Info=22 CmnHdr=1 AddrHdr=3 PathHdr=7 ExtHdrs=0 L4Hdr=1 L4Proto=UDP\nInfo: InfoF=7 HopF=9 IfID=57 Ingress=true SRev=SignedRevInfo: RevInfo: IA: 19-ffaa:0:1303 IfID: 57 Link type: child Timestamp: 2020-08-13 15:52:43+0000 TTL: 20s Sign: SignType: ed25519 Timestamp: 2020-08-13 15:52:43.000000+0000 SignSrc: 44454641554c543a2049413a2031392d666661613a303a3133303320434841494e3a2032205452433a2032 Signature: 6e24210e620180620e98b3918882120b38c03bd5d506d20218f82bedf3faa24cca538757aebc2d392ab83acb72061e79776d12633199ef543a828a28dde60905\nCmnHdr: 0041007a0b070911\nAddrHdr: 0013ffaa000101080012ffaa000012017f00000180ed98a5\nPathHdr: 015f35618a001202003f00000500f31c013f003000759054015f35618c001303013f0000058a2778003f0010396b8586003f001000306a0d\nExtHdrs: \nL4Hdr: 115b1adc0022d9a2\n" src="{IA:19-ffaa:0:1303 Host:141.44.25.144}"
2020/08/13 15:52:44 Class=PATH(3) Type=REVOKED_IF(4) TotalLen=296B Checksum=a612 Timestamp=2020-08-13 15:52:43.992268 +0000 UTC
```
I have started it again, please try one more time.
___
*[content/sigcomm/workshop.md, line 209 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhb_01GPRbcvkYZyq:-MEfw_7LB7OJcRFSVwPB:b-yflyh8) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L209)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

What is the point of this server? Should it be accessible over the SIG?
</blockquote></details>

That is my idea. I wanted them to access the server using a browser and the SIG


<!-- Sent from Reviewable.io -->

2020-08-14 09:59 UTC, mlegner requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[content/sigcomm/workshop.md, line 197 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhYZY6IBQ5FNgFDzk:-MEgOk0l6dmCqkIiIIMA:b-svf0qz) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L197)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it was down. This was in the log file:
```
starting SCION server on Thu Aug 13 15:48:18 UTC 2020
t=2020-08-13T15:48:18+0000 lvl=dbug msg="Registered with dispatcher" addr=18-ffaa:0:1201,128.237.152.165:4443
2020/08/13 15:52:33 19-ffaa:1:108,127.0.0.1:6876 "GET / HTTP/3/SCION" 200 20760
t=2020-08-13T15:52:44+0000 lvl=info msg="Received SCMP revocation" header="Class=PATH(3) Type=REVOKED_IF(4) TotalLen=296B Checksum=a612 Timestamp=2020-08-13 15:52:43.992268 +0000 UTC" payload="Meta: Info=22 CmnHdr=1 AddrHdr=3 PathHdr=7 ExtHdrs=0 L4Hdr=1 L4Proto=UDP\nInfo: InfoF=7 HopF=9 IfID=57 Ingress=true SRev=SignedRevInfo: RevInfo: IA: 19-ffaa:0:1303 IfID: 57 Link type: child Timestamp: 2020-08-13 15:52:43+0000 TTL: 20s Sign: SignType: ed25519 Timestamp: 2020-08-13 15:52:43.000000+0000 SignSrc: 44454641554c543a2049413a2031392d666661613a303a3133303320434841494e3a2032205452433a2032 Signature: 6e24210e620180620e98b3918882120b38c03bd5d506d20218f82bedf3faa24cca538757aebc2d392ab83acb72061e79776d12633199ef543a828a28dde60905\nCmnHdr: 0041007a0b070911\nAddrHdr: 0013ffaa000101080012ffaa000012017f00000180ed98a5\nPathHdr: 015f35618a001202003f00000500f31c013f003000759054015f35618c001303013f0000058a2778003f0010396b8586003f001000306a0d\nExtHdrs: \nL4Hdr: 115b1adc0022d9a2\n" src="{IA:19-ffaa:0:1303 Host:141.44.25.144}"
2020/08/13 15:52:44 Class=PATH(3) Type=REVOKED_IF(4) TotalLen=296B Checksum=a612 Timestamp=2020-08-13 15:52:43.992268 +0000 UTC
```
I have started it again, please try one more time.
</blockquote></details>

Still getting an error:
```
$ scion-bat 18-ffaa:0:1201,128.237.152.165:4443/
DBUG[08-14|09:56:04] Registered with dispatcher               addr=17-ffaa:1:d9b,127.0.0.1:6776
2020/08/14 09:56:14.347125 bat.go:228: Error Get https://[18-ffaa:0:1201,128.237.152.165]:4443/: NO_ERROR: Handshake did not complete in time
```
___
*[content/sigcomm/workshop.md, line 209 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhb_01GPRbcvkYZyq:-MEgOwc3BxiVJF8RwLZZ:bvxipz) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L209)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

That is my idea. I wanted them to access the server using a browser and the SIG
</blockquote></details>

Can we modify this part telling them that there is a webserver running at a private (non-routable) address `10.42.0.1`, which they can only access through the SIG, and link to the SIG task?


<!-- Sent from Reviewable.io -->

2020-08-14 13:25 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 209 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhb_01GPRbcvkYZyq:-MEh8F9S7RYpYlb2bA_o:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L209)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Can we modify this part telling them that there is a webserver running at a private (non-routable) address `10.42.0.1`, which they can only access through the SIG, and link to the SIG task?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-14 13:52 UTC, mlegner reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @juagargi and @mlegner)



<!-- Sent from Reviewable.io -->

2020-08-14 14:19 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 197 at r7](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEdhYZY6IBQ5FNgFDzk:-MEhKUKP1nZEgoEc6XpS:b-gjaxbf) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/40ae7c4c0080208e85ae0200e95c956e085517ae/content/sigcomm/workshop.md#L197)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Still getting an error:
```
$ scion-bat 18-ffaa:0:1201,128.237.152.165:4443/
DBUG[08-14|09:56:04] Registered with dispatcher               addr=17-ffaa:1:d9b,127.0.0.1:6776
2020/08/14 09:56:14.347125 bat.go:228: Error Get https://[18-ffaa:0:1201,128.237.152.165]:4443/: NO_ERROR: Handshake did not complete in time
```
</blockquote></details>

That happens when the server is not listening anymore. I could not reproduce whatever was happening, but I've modified the server to `ListendAndServe` inside an endless loop, so if there is a chance for the function to succeed at some point in time, it will grab it.


<!-- Sent from Reviewable.io -->

2020-08-14 14:59 UTC, mlegner requested changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 312 at r11](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEhTpDT6Ex9CCAYK5j8:-MEhTpDUEMFgP5EjEsTc:bx0l90w) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/b9acd10b490f4a408af8a98d713d73b950c7262d/content/sigcomm/workshop.md#L312)):*
> ```Markdown
> + Save the modified topology file
> + Copy the modified topology file into all subdirectories of `/etc/scion/gen/ISD*/AS*/` (all other services need to know the new topology) `sudo cp topology.json ../br*/ ; sudo cp topology.json ../cs*/`.
> + Restart SCION by calling `sudo systemctl restart scionlab.target`; you may also have to remove the contents of the directory `/var/lib/scion/`
> ```

I'm having issues with webapp after removing the contents of this directory.


<!-- Sent from Reviewable.io -->

2020-08-14 15:31 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 312 at r11](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEhTpDT6Ex9CCAYK5j8:-MEha2yv7huNY6yrNUfs:b9fginy) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/b9acd10b490f4a408af8a98d713d73b950c7262d/content/sigcomm/workshop.md#L312)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

I'm having issues with webapp after removing the contents of this directory.
</blockquote></details>

it has to be removed after stopping services, and before starting them again. I'm going to remove the sentence, it's actually not necessary.


<!-- Sent from Reviewable.io -->

2020-08-14 15:32 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)

___
*[content/sigcomm/workshop.md, line 312 at r11](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166#-MEhTpDT6Ex9CCAYK5j8:-MEhaY6rEPQ0ZDMGXkDL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/b9acd10b490f4a408af8a98d713d73b950c7262d/content/sigcomm/workshop.md#L312)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it has to be removed after stopping services, and before starting them again. I'm going to remove the sentence, it's actually not necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-14 15:33 UTC, juagargi reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mlegner)



<!-- Sent from Reviewable.io -->

2020-08-14 15:35 UTC, juagargi reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: all files reviewed, 2 unresolved discussions (waiting on @mlegner)



<!-- Sent from Reviewable.io -->

2020-08-14 15:51 UTC, mlegner approved these changes
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-14 15:53 UTC, merged