Update RAINS section in SCIONLab documentation
netsec-ethz/scion-tutorials pull request #188
Opened 2022-02-14 15:05 UTC by hyateh

2022-02-14 15:14 UTC, hausheer commented on content/apps/rains.md
> +~~If you want to run your own RAINS servers, please refer to the documentation in the [READMEs](https://github.com/netsec-ethz/rains).~~
I suggest to update the URL to the README as well.

2022-02-14 15:15 UTC, hausheer commented
Do we already have a test server running in SCIONLab that RAINS could be tested against? If so, it would be great to add it here.

2022-02-23 13:47 UTC, matzf commented
@hyateh Do you plan to update this following @hausheer's feedback? Let me know if you want me to merge this as is.

2022-02-23 13:57 UTC, hyateh commented
> @hyateh Do you plan to update this following @hausheer's feedback? Let me know if you want me to merge this as is.

A student (Robin) is looking into this but is somehow blocked by not knowing which SCIONLab servers can be used to set up the test RAINS servers. Do you happen to have a clue? :-)

2022-02-23 14:16 UTC, juagargi requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/188)* status: all files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[content/apps/rains.md, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/188#-MwavhyU3_DMbYV5Hotz:-MwavhyU3_DMbYV5Hou-:bhorbto) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/abbe30389b8905d08867932f2b3e325b0fee514a/content/apps/rains.md#L9)):*
> ```Markdown
> # RAINS, Another Internet Naming Service
> 
> {% include alert type="Info" content="The development of RAINS is now maintained [here](https://github.com/netsys-lab/scion-rains)". To set up and test the latest RAINS manually, please refer to the [instructions](https://github.com/netsys-lab/scion-rains/tree/master/test/manual). %}
> ```

We still use the existing `netsec-ethz/rains` in `scion-apps`.
Is RAINS going to be maintained now in the proposed repository?


<!-- Sent from Reviewable.io -->

2022-02-23 17:03 UTC, hyateh commented
> We still use the existing `netsec-ethz/rains` in `scion-apps`. Is RAINS going to be maintained now in the proposed repository?

Hi Juan, yes that's the current plan. The RAINS codebase will be hosted there by NetSys-Lab until at least the completion (expected July) of an externally funded project. After that, we need to figure out a proper transition of the codebase to RHINE.

2022-11-08 19:06 UTC, closed without merging

2022-11-08 19:07 UTC, hausheer commented
Superseded by https://github.com/netsec-ethz/scion-tutorials/pull/194